module.exports = {
  apps: [
    {
      name: 'yz-frontend',
      script: './.output/server/index.mjs',
      cwd: '/var/www/yz-construction',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '600M',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        NITRO_PORT: 3000,
        HOST: '127.0.0.1',
      },
      error_file: '/var/log/pm2/yz-frontend-error.log',
      out_file: '/var/log/pm2/yz-frontend-out.log',
      log_file: '/var/log/pm2/yz-frontend-combined.log',
      time: true,
    },
    {
      name: 'yz-backend',
      script: './dist/server.js',
      cwd: '/var/www/yz-construction/backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      error_file: '/var/log/pm2/yz-backend-error.log',
      out_file: '/var/log/pm2/yz-backend-out.log',
      log_file: '/var/log/pm2/yz-backend-combined.log',
      time: true,
    },
  ],
};
